package org.eln2.registry

import org.eln2.utils.OreData

val oreInformation = mutableListOf<OreData>(
    OreData(1, "acanthite", 5),
    OreData(1, "anthracite_coal", 5),
    OreData(1, "azurite", 4),
    OreData(1, "bauxite", 1),
    OreData(1, "bismuthinite", 2),
    OreData(1, "bituminous_coal", 2),
    OreData(1, "borax", 3),
    OreData(1, "cassiterite", 2),
    OreData(1, "cassiterite_rare", 3),
    OreData(1, "cattierite", 2),
    OreData(1, "cerussite", 3),
    OreData(1, "chalcocite", 3),
    OreData(1, "chalcopyrite", 3),
    OreData(1, "chromite", 2),
    OreData(1, "cinnabar", 3),
    OreData(1, "corundum", 2),
    OreData(1, "cryolite", 3),
    OreData(1, "eskolaite", 3),
    OreData(1, "fluorite", 3),
    OreData(1, "galena", 3),
    OreData(1, "graphite", 2),
    OreData(1, "halite", 2),
    OreData(1, "hematite", 3),
    OreData(1, "ilmenite", 2),
    OreData(1, "kernite", 3),
    OreData(1, "lepidolite", 2),
    OreData(1, "limonite", 3),
    OreData(1, "magnetite", 3),
    OreData(1, "malachite", 3),
    OreData(1, "millerite", 3),
    OreData(1, "native_copper", 3),
    OreData(1, "native_platnium", 3),
    OreData(1, "native_sulfur", 1),
    OreData(1, "pentlandite", 3),
    OreData(1, "petalite", 3),
    OreData(1, "psilomelane", 2),
    OreData(1, "pyrite", 3),
    OreData(1, "pyrolusite", 2),
    OreData(1, "quartz", 3),
    OreData(1, "rhodochrosite", 3),
    OreData(1, "rutile", 3),
    OreData(1, "scheelite", 2),
    OreData(1, "siderite", 3),
    OreData(1, "silver", 3),
    OreData(1, "smithsonite", 3),
    OreData(1, "sphalerite", 3),
    OreData(1, "spherocobaltite", 3),
    OreData(1, "spodumene", 3),
    OreData(1, "stannite", 2),
    OreData(1, "sylvite", 2),
    OreData(1, "tantalite", 3),
    OreData(1, "titanite", 2),
    OreData(1, "wolframite", 2)
)
